server:
  port: 8080
spring:
  datasource:
    username: root
    password: pyh903903
    url: jdbc:mysql://localhost:3306/hzone?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 120.77.13.126
    port: 6379
    password: pyh903903
#    cluster:
#      #各个节点
#      nodes: 120.77.13.126:6371,120.77.13.126:6372,120.77.13.126:6373,120.77.13.126:6374,120.77.13.126:6375,120.77.13.126:6376
#      # 最大重定向数
#      max-redirects: 6
