server:
  port: 8080
spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    #host: 120.77.13.126
    #port: 5672
    addresses: 127.0.0.1:5672
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: GMT+8  # 时区修改为东8区
  datasource:
    username: root
    password: pyh903903
    url: jdbc:mysql://localhost:3306/hzone?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password: pyh903903
#    cluster:
#      #各个节点
#      nodes: 120.77.13.126:6371,120.77.13.126:6372,120.77.13.126:6373,120.77.13.126:6374,120.77.13.126:6375,120.77.13.126:6376
#      # 最大重定向数
#      max-redirects: 6
  mail:
    host: smtp.qq.com
    username: hchier@qq.com
    password: roiifxpxjneqjcgi
    default-encoding: UTF-8



mybatis:
  #mapper-locations: classpath:hchier\springboot\mapper\*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #输出sql到控制台
    map-underscore-to-camel-case: true

