server:
  port: 9527

spring:
  application:
    name: gateway

  redis:
    host: 127.0.0.1
    port: 6379
    password: pyh903903

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://service-user
          predicates:
            - Path=/user/**

        - id: notice
          uri: lb://service-notice
          predicates:
            - Path=/notice/**

        - id: topic
          uri: lb://service-topic
          predicates:
            - Path=/topic/**

        - id: wall
          uri: lb://service-wall
          predicates:
            - Path=/wall/**

        - id: blog
          uri: lb://service-blog
          predicates:
            - Path=/blog/**

properties:
  # redis中存放token的hash
  hashForToken: tokens

  # 无需登录就可以访问的接口
  whitePaths: '{
    "/user/register":"null",
    "/user/login":"null",
    "/topic/incrReadNum":"null",
    "/topic/totalReadNumChart":"null",
    "/topic/weekReadNumChart":"null",
    "/topic/dayReadNumChart":"null"
  }'



#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'