server:
  port: 9527

spring:
  application:
    name: gateway

  redis:
    host: 127.0.0.1
    port: 6379
    password: pyh903903

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]': #拦截的请求
            #允许跨域的请求
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:63343"
            allowedMethods: #运行跨域的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" #允许请求中携带的头信息
            allowCredentials: true #是否允许携带cookie
            maxAge: 36000 #跨域检测的有效期,单位s

      routes:
        - id: ws
          #gateway转发ws有点儿问题
          #uri: lb:ws://service-ws
          uri: ws://localhost:8071
          predicates:
            - Path=/ws/**

        - id: user
          uri: lb://service-user
          predicates:
            - Path=/user/**

        - id: notice
          uri: lb://service-notice
          predicates:
            - Path=/notice/**

        - id: topic
          uri: lb://service-topic
          predicates:
            - Path=/topic/**

        - id: wall
          uri: lb://service-wall
          predicates:
            - Path=/wall/**

        - id: blog
          uri: lb://service-blog
          predicates:
            - Path=/blog/**

        - id: follow
          uri: lb://service-follow
          predicates:
            - Path=/follow/**

        - id: talk
          uri: lb://service-talk
          predicates:
            - Path=/talk/**

properties:
  # redis中存放token的hash
  hashForToken: tokens

  # 无需登录就可以访问的接口
  whitePaths: '{
    "/user/register":"null",
    "/user/login":"null",
    "/notice/sendAuthCode":"null",
    "/user/resetPassword":"null"
  }'



#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


