server:
  port: 8021


spring:
  application:
    name: service-topic

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    username: root
    password: pyh903903
    url: jdbc:mysql://localhost:3306/hzone?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


#properties:
#  # redis中存放token的hash
#  hashForToken: tokens
#
#  # redis中存放token过期时间的zset
#  zsetForTokenExpireTime: tokenExpireTime
#
#  # 验证码生存时长（秒）
#  authCodeLifeCycle: 300
#
#  # token的生存时长（分钟）
#  tokenLifeCycle: 3
#
#  # 无需登录就可以访问的接口
#  whitePaths: '{
#    "/user/register":"null",
#    "/user/login":"null",
#    "/topic/get":"null"
#  }'
#


mybatis:
  #mapper-locations: classpath:hchier\springboot\mapper\*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #输出sql到控制台
    map-underscore-to-camel-case: true