server:
  port: 8011

spring:
  application:
    name: service-notice

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    username: root
    password: pyh903903
    url: jdbc:mysql://localhost:3306/hzone?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.qq.com
    username: hchier@qq.com
    password: dynlazwgwhpshjbd
    default-encoding: UTF-8
    protocol: smtp

  redis:
    host: 127.0.0.1
    port: 6379
    password: pyh903903

  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    addresses: 127.0.0.1:5672
    listener:
      simple:
        acknowledge-mode: manual # 开启手动ack，
        retry:
          enabled: true #开启重试
          max-attempts: 3 #最大重试次数
          initial-interval: 2000ms  #重试间隔时间


properties:
  # 验证码生存时长（秒）
  authCodeLifeCycle: 300
